name: "Minimul tag creator"
description: "Minimul kit GitHub tag creator"
inputs:
  ref:
    description: Branch head ref (should leave this default).
    required: true
    default: ${{ github.head_ref }}
  token:
    description: GITHUB_TOKEN.
    required: true
    default: ${{ github.token }}
  version_file:
    description: Version file to keep track of latest version. (defaults to version.txt)
    required: true
    default: "version.txt"
  skip_ci:
    description: Specifies if change to version_file should skip CI, valid values are "true" or "false", defaults to "true".
    required: true
    default: "true"
  skip_ci_commit_string:
    description: If skip_ci == true, specifies string appended to commit, defaults to "[skip ci]".
    required: false
    default: "[skip ci]"
runs:
  using: node12
  main: dist/bundle.js